HomieBundle\Entity\Available:
    type: entity
    table: null
    repositoryClass: HomieBundle\Repository\AvailableRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime

    manyToMany:
        user:
            targetEntity: HomieBundle\Entity\User
            mappedBy: availables
    lifecycleCallbacks: {  }
