HomieBundle\Entity\Available:
    type: entity
    table: null
    repositoryClass: HomieBundle\Repository\AvailableRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        start_date:
            type: datetime

        end_date:
            type: datetime

    manyToOne:
        user:
            targetEntity: HomieBundle\Entity\User
            inversedBy: availables
            nullable: true
            cascade: ["all"]

    lifecycleCallbacks: {  }
