HomieBundle\Entity\Checkout:
    type: entity
    table: null
    repositoryClass: HomieBundle\Repository\CheckoutRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
            nullable: true

        address:
            type: string
            length: 255
            nullable: true

        quantity:
            type: integer

    manyToOne:
        meals:
            targetEntity: HomieBundle\Entity\Meal

        cook:
            targetEntity: HomieBundle\Entity\User

        client:
            targetEntity: HomieBundle\Entity\User
            inversedBy: checkouts

        confirm:
            targetEntity: HomieBundle\Entity\Confirm

    lifecycleCallbacks: {  }
