HomieBundle\Entity\Confirm:
    type: entity
    table: null
    repositoryClass: HomieBundle\Repository\ConfirmRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
