HomieBundle\Entity\Meal:
    type: entity
    table: null
    repositoryClass: HomieBundle\Repository\MealRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        delay:
            type: integer
    lifecycleCallbacks: {  }
