HomieBundle\Entity\Meal:
    type: entity
    table: null
    repositoryClass: HomieBundle\Repository\MealRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        delay:
            type: integer
        price:
            type: integer

    manyToMany:
        users:
            targetEntity: HomieBundle\Entity\User
            mappedBy: meals
            nullable: true

        availables:
            targetEntity: HomieBundle\Entity\Available
            inversedBy: meals
            nullable: true


    manyToOne:
        meal_type:
            targetEntity: HomieBundle\Entity\Meal_type

    oneToOne:
        photo:
            targetEntity: HomieBundle\Entity\Photo

    lifecycleCallbacks: {  }
