HomieBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: HomieBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        address1:
            type: string
            length: 255
            nullable: true
        address2:
            type: string
            length: 255
            nullable: true
        phone:
            type: integer
            nullable: true
        description:
            type: text
            nullable: true

        online:
            type: boolean

    oneToMany:
        availables:
            targetEntity: HomieBundle\Entity\Available
            mappedBy: user
            nullable: true
            cascade: ["all"]
    manyToMany:
        meals:
            targetEntity: HomieBundle\Entity\Meal
            inversedBy: users
            nullable: true

    oneToOne:
        photo:
            targetEntity: HomieBundle\Entity\Photo

    manyToOne:
        userGroup:
            targetEntity: HomieBundle\Entity\UserGroup


    lifecycleCallbacks: {  }
