HomieBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: HomieBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:

        street:
            type: string
            length: 255
            nullable: true

        zip_code:
            type: integer
            nullable: true

        town:
            type: string
            length: 255
            nullable: true

        digicode:
            type: string
            length: 20
            nullable: true

        complement:
            type: string
            length: 255
            nullable: true

        street2:
            type: string
            length: 255
            nullable: true

        zip_code2:
            type: integer
            nullable: true

        town2:
            type: string
            length: 255
            nullable: true

        digicode2:
            type: string
            length: 20
            nullable: true

        complement2:
            type: string
            length: 255
            nullable: true

        phone:
            type: integer
            nullable: true
        description:
            type: text
            nullable: true

        online:
            type: boolean
            nullable: true

    oneToMany:
        availables:
            targetEntity: HomieBundle\Entity\Available
            mappedBy: user
            nullable: true
            cascade: ["all"]

        checkouts:
            targetEntity: HomieBundle\Entity\Checkout
            mappedBy: client
            nullable: true

    manyToMany:
        meals:
            targetEntity: HomieBundle\Entity\Meal
            inversedBy: users
            nullable: true

    oneToOne:
        photo:
            targetEntity: HomieBundle\Entity\Photo

    manyToOne:
        userGroup:
            targetEntity: HomieBundle\Entity\UserGroup


    lifecycleCallbacks: {  }
