<?php

namespace HomieBundle\Repository;
use HomieBundle\Entity\User;

/**
 * CheckoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckoutRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNbCheckout(User $user)
    {
        $userId = $user->getId();
        return $this->createQueryBuilder('c')
            ->andWhere('c.client = :userid')
            ->andWhere('c.confirm = :sendid')
            ->setParameter('userid', $userId)
            ->setParameter('sendid', 1)
            ->select('SUM(c.quantity)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function findCheckouts(User $user) {
        $userId = $user->getId();
        return $this->createQueryBuilder('c')
            ->andWhere('c.client = :userid')
            ->setParameter('userid', $userId)
            ->getQuery()
            ->getResult();
    }

    public function price(User $user) {
        $userId = $user->getId();
        return $this->createQueryBuilder('c')
            ->andWhere('c.client = :userid')
            ->setParameter('userid', $userId)
            ->select('SUM(c.price)')
            ->getQuery()
            ->getSingleScalarResult();
    }

}
