<?php

namespace HomieBundle\Repository;

/**
 * ConfirmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfirmRepository extends \Doctrine\ORM\EntityRepository
{
}
