<?php

namespace HomieBundle\Repository;

/**
 * CooksmealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CooksmealRepository extends \Doctrine\ORM\EntityRepository
{
}
