<?php

namespace HomieBundle\Repository;

/**
 * Meal_typeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Meal_typeRepository extends \Doctrine\ORM\EntityRepository
{
}
